### ISSUE TITLE
Can't load image through the given file path

### ISSUE THREAD

**Issue by lawncegoh** [nus-cs2103-AY1920S1/forum#45] opened 2019-09-05 11:50 UTC
**Have these 2 lines in my duke main class.** 

private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png "));
private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png "));

**These are the file paths:**

/Users/lawnce/Desktop/duke/src/main/resources/images/DaUser.png 
/Users/lawnce/Desktop/duke/src/main/resources/images/DaDuke.png 

This is the error i encounter. I tried solving through the Slack channel's way of renaming the file directly to resources or adding / in front of images but it doesn't work somehow

<img width="1038" alt="Screenshot 2019-09-05 at 11 29 28 AM" src="https://user-images.githubusercontent.com/48293591/64339637-08161180-d017-11e9-991e-68e65d10e8e1.png">

**Comment by damithc** [comment] 2019-09-05 13:59
Can you post the code to a branch and give the link here?

**Comment by lawncegoh** [comment] 2019-09-05 17:16
Hi Prof, 

This is the link my duke.java

https://github.com/lawncegoh/duke/blob/master/src/main/java/Duke.java

**Comment by damithc** [comment] 2019-09-06 00:44
Just one file is not enough. Someone should be able to reproduce the problem by cloning your repo. Are all the relevant files in the master branch? If not, push the current state of the repo to a separate branch and give the link to the branch.

**Comment by kylase-learning** [comment] 2019-09-06 00:49
Please read this to find out how to access file in your resources folder https://www.mkyong.com/java/java-read-a-file-from-resources-folder/

**Comment by lawncegoh** [comment] 2019-09-06 05:35
https://github.com/lawncegoh/duke/tree/master/src/main

**Comment by damithc** [comment] 2019-09-06 05:40
@j-lum can help?

**Comment by j-lum** [comment] 2019-09-06 06:00
![image](https://user-images.githubusercontent.com/22460123/64404439-8c67a380-d0ae-11e9-984f-f5e1e777ea73.png)
Unable to reproduce error from cloning your repo.

**Comment by damithc** [comment] 2019-09-06 11:17
Works or me too.
![image](https://user-images.githubusercontent.com/1673303/64424176-ea11e500-d0da-11e9-9587-241ca439ce6e.png)

**Comment by dawo5010** [comment] 2019-09-06 12:07
I cloned your repo and managed to replicate the error:

<img width="1680" alt="Screenshot 2019-09-06 at 8 03 46 PM" src="https://user-images.githubusercontent.com/4518827/64426559-74f5de00-d0e1-11e9-80be-2facf55d1944.png">

The issue at hand is quite easily fixed: simply remove the trailing space after the file path for the two statements you posted:

`private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png "));
private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png "));`
to
`private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));`

The program executes successfully:
<img width="512" alt="Screenshot 2019-09-06 at 8 05 18 PM" src="https://user-images.githubusercontent.com/4518827/64426632-ac648a80-d0e1-11e9-91e1-f4791f6decf9.png">

I infer that you're on Mac OS from the directory structure your indicated. It seems that Prof and Jeffry didn't encounter the issue as Mac OS/Unix systems in general are much more anal than Windows when it comes to file naming conventions (being case-sensitive by default, amongst other things).

Hope that helps and don't forget to close the issue if it's been resolved!

**Closed** 2019-09-07 10:01 UTC
Labels: type-HelpRequest :sos:, week.4
