### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by alages97** [nus-cs2103-AY1920S1/forum#38] opened 2019-09-02 16:10 UTC
I'm somehow getting an invocationtargetexception in the fxmlloader.java file when i try to return a String in my getResponse method. Any idea why i'm getting this error?

**Comment by j-lum** [comment] 2019-09-02 16:56
https://stackoverflow.com/help/how-to-ask

**Comment by damithc** [comment] 2019-09-05 06:42
Closing for now. @alages97 please reopen with more details if the issue is still unresolved.

**Closed by damithc** 2019-09-05 06:42 UTC
Labels: type-HelpRequest :sos:, week.4
